---
title: "Home"
author: "Bastián González-Bustamante"
affiliation: "University of Oxford"
date: "December 2019"
---

# Chilean Political Science Impact Ranking
  
This ranking is presented from the highest to the lowest H-Index.^[The number of cites has been used as a second criterion in case of a tie in H-Index.] It has been elaborated according to the following sampling criteria. First of all, all the paper-givers with a Chilean academic affiliation in the last political science congress organised by the Chilean Association of Political Science in 2018 were identified. After that, people considered was those who possed an active Google Scholar account. Subsequently, well-known researchers in the Chilean field, who also possess a Google Scholar profile, suggested by other people who were selected in the previous step were added.^[If you like to suggest someone, please send an email to bastian.gonzalezbustamante@politics.ox.ac.uk] Finally, authors who had added to their profile publications that are not their authorship (because of name confusion, deliberately or without realising it) have been removed from the ranking.^[I would like to thank Alejandro Olivares, Carla Cisternas, and Rodrigo Cuevas for their valuable comments and contributions.]

The first measurement has been collected on 2 December, 2019. The next one will be collected by March 2020.^[Researchers to be added: Marcelo Mella Polanco (ID qdm2fHgAAAAJ), Hary Hugo Fruhling (ID dJKWN8wAAAAJ), Arturo Arriagada (ID TzPYdWsAAAAJ), Jorge Gordin (ID RJp2E7cAAAAJ), Stefano Palestini (ID 1JylyXQAAAAJ), Ross Mittiga (ID o4ZnQNsAAAAJ), Alfonso Donoso (ID OrPr-3AAAAAJ), Giovanni Agostinis (ID u9c4q20AAAAJ), Antonio Canale-Mayet (ID dFcoyfMAAAAJ), Javier Sajuria (ID elmJq2gAAAAJ), Federico Rojas-de-Galarreta (ID hTyE9WAAAAAJ), and Ximena Soto Soutullo (ID r2q0t8cAAAAJ&hl). Last updated: 23 December 2019.]

The dataset can be downloaded from the OSF project (DOI: [10.17605/OSF.IO/C8PRA](http://doi.org/10.17605/OSF.IO/C8PRA)).
