baseurl = "~shil5311/ranking/"
title = "Chilean Political Science Impact Ranking"
DefaultContentLanguage = "en"
metaDataFormat = "yaml"

[Author]
  name = "Basti치n Gonz치lez-Bustamante"
  ## website = "http://users.ox.ac.uk/~shil5311/"
  
[params]
  footer = "&copy; [Basti치n Gonz치lez-Bustamante](http://users.ox.ac.uk/~shil5311/) (2019)"

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1
    
[[menu.main]]
    name = "Series"
    url = "/series"
    weight = 2
    
[[menu.main]]
    name = "Careers"
    url = "/careers"
    weight = 3

[[menu.main]]
    name = "Networks"
    url = "/networks"
    weight = 4

[[menu.main]]
    name = "Changelog"
    url = "/Changelog"
    weight = 5
    
